from PyQt4 import QtCore, QtGui, Qt
from EditorMisc import Constants


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s


try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 639)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setStatusTip(_fromUtf8(""))
        MainWindow.setWhatsThis(_fromUtf8(""))
        MainWindow.setAccessibleName(_fromUtf8(""))
        MainWindow.setAccessibleDescription(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(630, 10, 160, 80))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))

        # central panel - label
        self.add_central_label()

        # central panel - sliders
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 10, 181, 331))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.add_sliders()

        # central panel - fears
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(300, 356, 181, 81))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.add_fear_combo_boxes()

        # left panel
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 175, 584)) # increase last param by 23 for each new checkbox
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.add_scenario_combo_box()
        self.add_set_bytes_button()
        self.add_global_ghost_level_combo_box()
        self.add_normal_check_boxes()
        self.add_recommended_label()
        self.add_recommended_check_boxes()

        # right panel
        self.add_mortal_combo_box()

        # scenario panel
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(180, 10, 111, 186))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.add_scenario_label()
        self.add_scenario_spin_boxes()
        self.add_plasm_line_edit()
        self.add_mood_combo_box()
        self.add_manual_terror_check_box()

        #
        MainWindow.setCentralWidget(self.centralwidget)
        self.add_menu_bar(MainWindow)
        self.add_status_bar(MainWindow)
        self.retranslateUi(MainWindow)
        self.add_object_connections(MainWindow)
        self.integrity_dialog = IntegrityCheckDialog(self)

    # combo boxes
    def add_scenario_combo_box(self):
        self.comboBox_3 = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem("")
        self.comboBox_3.setEnabled(False)
        self.verticalLayout_3.addWidget(self.comboBox_3)

    def add_mortal_combo_box(self):
        self.comboBox_4 = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem("")
        self.comboBox_4.setEnabled(False)
        self.verticalLayout.addWidget(self.comboBox_4)

    def add_fear_combo_boxes(self):
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setEnabled(False)
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(15, _fromUtf8(""))
        self.comboBox_2.setEnabled(False)
        self.gridLayout.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.setItemText(15, _fromUtf8(""))
        self.comboBox_6.setEnabled(False)
        self.gridLayout.addWidget(self.comboBox_6, 1, 0, 1, 1)

    def add_global_ghost_level_combo_box(self):
        self.comboBox_7 = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.setToolTip(Constants.GLOBAL_GHOST_LEVEL)
        self.comboBox_7.setEnabled(False)
        self.verticalLayout_3.addWidget(self.comboBox_7)

    def add_mood_combo_box(self):
        self.comboBox_5 = QtGui.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.setEnabled(False)
        self.comboBox_5.setHidden(True)
        self.verticalLayout_4.addWidget(self.comboBox_5)

    # check boxes
    def add_normal_check_boxes(self):
        self.checkBox1 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox1.setObjectName(_fromUtf8("checkBox_1"))
        self.checkBox1.setToolTip(Constants.UNLIMITED_PLASM)
        self.checkBox1.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox1)
        self.checkBox2 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox2.setToolTip(Constants.UNLIMITED_GOLDPLASM)
        self.checkBox2.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox2)
        self.checkBox3 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox3.setToolTip(Constants.INSTANT_POWER_RECHARGE)
        self.checkBox3.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox3)
        self.checkBox18 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox18.setObjectName(_fromUtf8("checkBox_18"))
        self.checkBox18.setToolTip(Constants.CONTINUOUS_POWER_RECASTING)
        self.checkBox18.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox18)
        self.checkBox4 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox4.setToolTip(Constants.RESPONSIVE_EMPTY_PORTRAITS)
        self.checkBox4.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox4)
        self.checkBox5 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox5.setToolTip(Constants.GHOST_CLONING)
        self.checkBox5.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox5)
        self.checkBox9 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox9.setObjectName(_fromUtf8("checkBox_9"))
        self.checkBox9.setToolTip(Constants.FETTER_SHARING)
        self.checkBox9.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox9)
        self.checkBox6 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox6.setToolTip(Constants.INSIDE_OUTSIDE_ON_ALL_GHOSTS)
        self.checkBox6.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox6)
        self.checkBox10 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkBox10.setToolTip(Constants.MOVABLE_RESTLESS_GHOSTS)
        self.checkBox10.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox10)
        self.checkBox7 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkBox7.setToolTip(Constants.IGNORE_WARDS)
        self.checkBox7.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox7)
        self.checkBox12 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox12.setObjectName(_fromUtf8("checkBox_12"))
        self.checkBox12.setToolTip(Constants.UNCOVER_FEARS)
        self.checkBox12.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox12)
        self.checkBox14 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox14.setObjectName(_fromUtf8("checkBox_14"))
        self.checkBox14.setToolTip(Constants.DISABLE_CALMING_EFFECTS)
        self.checkBox14.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox14)
        self.checkBox15 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox15.setObjectName(_fromUtf8("checkBox_15"))
        self.checkBox15.setToolTip(Constants.UNLOCK_EXTRA_FEARS)
        self.checkBox15.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox15)
        self.checkBox16 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox16.setObjectName(_fromUtf8("checkBox_16"))
        self.checkBox16.setToolTip(Constants.FIX_COLD_PHOBIA)
        self.checkBox16.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox16)
        self.checkBox20 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox20.setObjectName(_fromUtf8("checkBox_20"))
        self.checkBox20.setToolTip(Constants.EXPLORATION_MODE)
        self.checkBox20.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox20)

    def add_recommended_check_boxes(self):
        self.checkBox8 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkBox8.setToolTip(Constants.DISABLE_FIRE_EXTINGUISHERS)
        self.checkBox8.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox8)
        self.checkBox11 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox11.setObjectName(_fromUtf8("checkBox_11"))
        self.checkBox11.setToolTip(Constants.DISABLE_MADNESS_IMMUNITY)
        self.checkBox11.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox11)
        self.checkBox13 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox13.setObjectName(_fromUtf8("checkBox_13"))
        self.checkBox13.setToolTip(Constants.UNLOCK_MISSING_FEARS)
        self.checkBox13.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox13)
        self.checkBox19 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox19.setObjectName(_fromUtf8("checkBox_19"))
        self.checkBox19.setToolTip(Constants.GHOST_RETRAINING)
        self.checkBox19.setEnabled(False)
        self.verticalLayout_3.addWidget(self.checkBox19)

    def add_manual_terror_check_box(self):
        self.checkBox17 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox17.setObjectName(_fromUtf8("checkBox_17"))
        self.checkBox17.setToolTip(Constants.MANUAL_TERROR)
        self.checkBox17.setEnabled(False)
        self.checkBox17.setHidden(True)
        self.verticalLayout_4.addWidget(self.checkBox17)

    # labels
    def add_central_label(self):
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 0, 181, 41))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))

    def add_recommended_label(self):
        self.line_1 = QtGui.QFrame(self.verticalLayoutWidget_3)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.verticalLayout_3.addWidget(self.line_1)

        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)

        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)

    def add_scenario_label(self):
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_2.setHidden(True)
        self.verticalLayout_4.addWidget(self.label_2)

    # misc
    def add_set_bytes_button(self):
        self.pushButton_9 = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_9.setEnabled(False)
        self.verticalLayout_3.addWidget(self.pushButton_9)

    def add_sliders(self):
        spacerItem = QtGui.QSpacerItem(0, 22, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)

        self.horizontalSlider = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalSlider.setEnabled(False)
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.horizontalSlider_4 = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.horizontalSlider_4.setEnabled(False)
        self.verticalLayout_2.addWidget(self.horizontalSlider_4)
        self.horizontalSlider_2 = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.horizontalSlider_2.setEnabled(False)
        self.verticalLayout_2.addWidget(self.horizontalSlider_2)
        self.horizontalSlider_3 = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.horizontalSlider_3.setEnabled(False)
        self.verticalLayout_2.addWidget(self.horizontalSlider_3)

        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider_2.setMinimum(0)
        self.horizontalSlider_3.setMinimum(0)
        self.horizontalSlider_4.setMinimum(0)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_3.setMaximum(100)
        self.horizontalSlider_4.setMaximum(100)
        self.horizontalSlider.tickInterval = 1
        self.horizontalSlider_2.tickInterval = 1
        self.horizontalSlider_3.tickInterval = 1
        self.horizontalSlider_4.tickInterval = 1
        self.horizontalSlider.setSingleStep(0)
        self.horizontalSlider_2.setSingleStep(0)
        self.horizontalSlider_3.setSingleStep(0)
        self.horizontalSlider_4.setSingleStep(0)
        self.horizontalSlider.setPageStep(0)
        self.horizontalSlider_2.setPageStep(0)
        self.horizontalSlider_3.setPageStep(0)
        self.horizontalSlider_4.setPageStep(0)

        #self.horizontalSlider_2.setStyleSheet("background: rgb(238, 156, 0)")
        #self.horizontalSlider_3.setStyleSheet("background: rgb(0, 178, 235)")
        #self.horizontalSlider_4.setStyleSheet("background: rgb(223, 0, 41)")

    def add_scenario_spin_boxes(self):
        self.spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_4)
        self.spinBox.setProperty("value", 0)
        self.spinBox.setMinimum(0)
        self.spinBox.setMaximum(8)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.spinBox.setEnabled(False)
        self.spinBox.setHidden(True)
        self.verticalLayout_4.addWidget(self.spinBox)
        self.spinBox_2 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.spinBox_2.setProperty("value", 0)
        self.spinBox_2.setMinimum(0)
        self.spinBox_2.setMaximum(100)
        self.spinBox_2.setDecimals(23)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setHidden(True)
        self.verticalLayout_4.addWidget(self.spinBox_2)

    def add_plasm_line_edit(self):
        self.lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit.setEnabled(False)
        self.lineEdit.setHidden(True)
        self.verticalLayout_4.addWidget(self.lineEdit)

    def add_menu_bar(self, MainWindow):
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpen.setShortcut(QtGui.QKeySequence("Ctrl+Z"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave.setShortcut(QtGui.QKeySequence("Ctrl+C"))
        self.actionSave.setEnabled(False)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))

        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuMenu.addAction(self.actionOpen)
        self.menuMenu.addAction(self.actionSave)
        self.menuMenu.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.actionScripts = QtGui.QAction(MainWindow)
        self.actionScripts.setObjectName(_fromUtf8("actionScripts"))
        self.actionScripts.setEnabled(False)
        self.menubar.addAction(self.actionScripts)

    def add_status_bar(self, MainWindow):
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", Constants.VERSION, None))
        self.label.setText(_translate("MainWindow", "Open the file", None))
        self.label_2.setText(_translate("MainWindow", "Scenario name", None))
        self.label_3.setText(_translate("MainWindow", "Recommended:", None))
        self.horizontalSlider.setStatusTip(_translate("MainWindow", "Willpower", None))
        self.horizontalSlider_2.setStatusTip(_translate("MainWindow", "Insanity", None))
        self.horizontalSlider_3.setStatusTip(_translate("MainWindow", "Belief", None))
        self.horizontalSlider_4.setStatusTip(_translate("MainWindow", "Terror", None))
        self.checkBox1.setText(_translate("MainWindow", "Unlimited Plasm", None))
        self.checkBox2.setText(_translate("MainWindow", "Unlimited Gold Plasm", None))
        self.checkBox3.setText(_translate("MainWindow", "Instant Power Recharge", None))
        self.checkBox4.setText(_translate("MainWindow", "Responsive Empty Portraits", None))
        self.checkBox5.setText(_translate("MainWindow", "Ghost Cloning", None))
        self.checkBox6.setText(_translate("MainWindow", "Inside/Outside On All Ghosts", None))
        self.checkBox7.setText(_translate("MainWindow", "Ignore Wards", None))
        self.checkBox8.setText(_translate("MainWindow", "Disable Fire Extinguishers", None))
        self.checkBox9.setText(_translate("MainWindow", "Fetter Sharing", None))
        self.checkBox10.setText(_translate("MainWindow", "Movable Restless Ghosts", None))
        self.checkBox11.setText(_translate("MainWindow", "Disable Madness Immunity", None))
        self.checkBox12.setText(_translate("MainWindow", "Uncover Fears", None))
        self.checkBox13.setText(_translate("MainWindow", "Unlock Missing Fears", None))
        self.checkBox14.setText(_translate("MainWindow", "Disable Calming Effects", None))
        self.checkBox15.setText(_translate("MainWindow", "Unlock Extra Fears", None))
        self.checkBox16.setText(_translate("MainWindow", "Fix Cold Phobia", None))
        self.checkBox17.setText(_translate("MainWindow", "Manual Terror", None))
        self.checkBox18.setText(_translate("MainWindow", "Continuous Power Recasting", None))
        self.checkBox19.setText(_translate("MainWindow", "Ghost Retraining", None))
        self.checkBox20.setText(_translate("MainWindow", "Exploration Mode (Alpha)", None))
        self.comboBox.setStatusTip(_translate("MainWindow", "Concious fear", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "none", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "blood", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "cold*", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "creepy", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "darkness", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "electrical", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "fire", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "hunted", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "noise", None))
        self.comboBox.setItemText(9, _translate("MainWindow", "normal", None))
        self.comboBox.setItemText(10, _translate("MainWindow", "storm", None))
        self.comboBox.setItemText(11, _translate("MainWindow", "trapped", None))
        self.comboBox.setItemText(12, _translate("MainWindow", "unclean", None))
        self.comboBox.setItemText(13, _translate("MainWindow", "water", None))
        self.comboBox.setItemText(14, _translate("MainWindow", "pursuit*", None))
        self.comboBox.setItemText(15, _translate("MainWindow", "", None))
        self.comboBox_2.setStatusTip(_translate("MainWindow", "Unconcious fear", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "none", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "blood", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "cold*", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "creepy", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "darkness", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "electrical", None))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "fire", None))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "hunted", None))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "noise", None))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "normal", None))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "storm", None))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "trapped", None))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "unclean", None))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "water", None))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "pursuit*", None))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "", None))
        self.comboBox_6.setStatusTip(_translate("MainWindow", "Extra concious fear", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "none", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "blood", None))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "cold*", None))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "creepy", None))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "darkness", None))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "electrical", None))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "fire", None))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "hunted", None))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "noise", None))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "normal", None))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "storm", None))
        self.comboBox_6.setItemText(11, _translate("MainWindow", "trapped", None))
        self.comboBox_6.setItemText(12, _translate("MainWindow", "unclean", None))
        self.comboBox_6.setItemText(13, _translate("MainWindow", "water", None))
        self.comboBox_6.setItemText(14, _translate("MainWindow", "pursuit*", None))
        self.comboBox_6.setItemText(15, _translate("MainWindow", "", None))
        self.comboBox_3.setStatusTip(_translate("MainWindow", "Scenarios", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "pick scenario", None))
        self.comboBox_4.setStatusTip(_translate("MainWindow", "Mortals", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "pick mortal", None))
        self.comboBox_5.setStatusTip(_translate("MainWindow", "Mood (scenario-wide)", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "none", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "neutral", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "friendly", None))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "angry", None))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "calm", None))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "rattled", None))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "terrified", None))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "insane", None))
        self.comboBox_5.setItemText(8, _translate("MainWindow", " ", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "global ghost level: off", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "global ghost level: 0", None))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "global ghost level: 1", None))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "global ghost level: 2", None))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "global ghost level: 3", None))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "global ghost level: 4", None))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "global ghost level: 5", None))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "global ghost level: 6", None))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "global ghost level: 7", None))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "global ghost level: 8", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionScripts.setText(_translate("MainWindow", "Scripts", None))
        self.spinBox.setStatusTip(_translate("MainWindow", "Haunter Slots", None))
        self.spinBox_2.setStatusTip(_translate("MainWindow", "Mean Terror", None))
        self.lineEdit.setStatusTip(_translate("MainWindow", "Starting Plasm (estimate)", None))
        self.pushButton_9.setText(_translate("MainWindow", "Set bytes @ address\nUSE AT OWN RISK", None))

    def add_object_connections(self, MainWindow):
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.sliderMoved)
        QtCore.QObject.connect(self.horizontalSlider_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.sliderMoved)
        QtCore.QObject.connect(self.horizontalSlider_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.sliderMoved)
        QtCore.QObject.connect(self.horizontalSlider_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.sliderMoved)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderReleased()")), MainWindow.setWillpower)
        QtCore.QObject.connect(self.horizontalSlider_2, QtCore.SIGNAL(_fromUtf8("sliderReleased()")), MainWindow.setInsanity)
        QtCore.QObject.connect(self.horizontalSlider_3, QtCore.SIGNAL(_fromUtf8("sliderReleased()")), MainWindow.setBelief)
        QtCore.QObject.connect(self.horizontalSlider_4, QtCore.SIGNAL(_fromUtf8("sliderReleased()")), MainWindow.setTerror)
        QtCore.QObject.connect(self.checkBox1, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setUnlimitedPlasm)
        QtCore.QObject.connect(self.checkBox2, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setUnlimitedGoldplasm)
        QtCore.QObject.connect(self.checkBox3, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setInstantPowerRecharge)
        QtCore.QObject.connect(self.checkBox4, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setResponsivePortraits)
        QtCore.QObject.connect(self.checkBox5, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setGhostCloning)
        QtCore.QObject.connect(self.checkBox6, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setInsideOutsideOnAll)
        QtCore.QObject.connect(self.checkBox7, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setIgnoreWards)
        QtCore.QObject.connect(self.checkBox8, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setDisableFireExtinguishers)
        QtCore.QObject.connect(self.checkBox9, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setFetterSharing)
        QtCore.QObject.connect(self.checkBox10, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setMovableRestlessGhosts)
        QtCore.QObject.connect(self.checkBox11, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setDisableMadnessImmunity)
        QtCore.QObject.connect(self.checkBox12, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setUncoverFears)
        QtCore.QObject.connect(self.checkBox13, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setUnlockMissingFears)
        QtCore.QObject.connect(self.checkBox14, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setDisableCalmingEffects)
        QtCore.QObject.connect(self.checkBox15, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setUnlockExtraFears)
        QtCore.QObject.connect(self.checkBox16, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setFixColdPhobia)
        QtCore.QObject.connect(self.checkBox17, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setManualTerror)
        QtCore.QObject.connect(self.checkBox18, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setContinuousPowerRecasting)
        QtCore.QObject.connect(self.checkBox19, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setGhostRetraining)
        QtCore.QObject.connect(self.checkBox20, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.setExplorationMode)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setConciousFear)
        QtCore.QObject.connect(self.comboBox_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setUnconciousFear)
        QtCore.QObject.connect(self.comboBox_6, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setExtraFear)
        QtCore.QObject.connect(self.comboBox_3, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.scenarioChanged)
        QtCore.QObject.connect(self.comboBox_4, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.mortalChanged)
        QtCore.QObject.connect(self.comboBox_5, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setMood)
        QtCore.QObject.connect(self.comboBox_7, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setGhostLevel)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.open_data)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.save_data)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.about)
        QtCore.QObject.connect(self.actionScripts, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.show_scripts_window)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.setHaunterSlots)
        QtCore.QObject.connect(self.spinBox_2, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.setMeanTerror)
        QtCore.QObject.connect(self.pushButton_9, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.setBytesAtAddress)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


class IntegrityCheckDialog(QtGui.QDialog):
    def __init__(self, parent=None):
        super(IntegrityCheckDialog, self).__init__(parent)
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setWindowTitle("Integrity Check")
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)

        self.splitter = QtGui.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)

        self.label = QtGui.QLabel(self.splitter)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.splitter)
        self.plainTextEdit.setFixedSize(360, 150)
        self.plainTextEdit.setReadOnly(True)
        self.label_2 = QtGui.QLabel(self.splitter)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)

        self.horizontalLayout.addWidget(self.splitter)


class ScriptsWindow(QtGui.QDialog):
    def __init__(self, parent):
        super(ScriptsWindow, self).__init__(parent)
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setWindowTitle("Scripts")
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)

        self.scroll_area_content = QtGui.QWidget()
        self.scroll_area = QtGui.QScrollArea(self)
        self.scroll_area.setWidget(self.scroll_area_content)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setFixedSize(600, 600)

        self.grid_layout = QtGui.QGridLayout(self.scroll_area_content)

    def setupCheckBoxes(self, scripts):
        for idx, elem in enumerate(scripts):
            nr = str(idx + 1).zfill(3)
            script_name = elem[2]
            comment = elem[3]
            checkBox = QtGui.QCheckBox()
            checkBox.setObjectName(_fromUtf8("checkBox_scr_%d" % idx))
            checkBox.setText(_translate("MainWindow", "%s - %s%s" % (nr, script_name, comment), None))
            checkBox.clicked.connect(self.parent().setScript)
            self.grid_layout.addWidget(checkBox, idx + 1, 0)

        self.horizontalLayout.addWidget(self.scroll_area)
